module.exports =
  LOAD: 'ADMIN:FORMS:LOAD'
  LOAD_SUCCESS: 'ADMIN:FORMS:LOAD_SUCCESS'
  LOAD_FAILURE: 'ADMIN:FORMS:LOAD_FAILURE'
  CREATE: 'ADMIN:FORMS:CREATE'
  CREATE_SUCCESS: 'ADMIN:FORMS:CREATE_SUCCESS'
  CREATE_FAILURE: 'ADMIN:FORMS:CREATE_FAILURE'
