module.exports =
  LOAD: 'ADMIN:EVENTS:LOAD'
  LOAD_SUCCESS: 'ADMIN:EVENTS:LOAD_SUCCESS'
  LOAD_FAILURE: 'ADMIN:EVENTS:LOAD_FAILURE'
  CREATE: 'ADMIN:EVENTS:CREATE'
  CREATE_SUCCESS: 'ADMIN:EVENTS:CREATE_SUCCESS'
  CREATE_FAILURE: 'ADMIN:EVENTS:CREATE_FAILURE'
