module.exports =
  AUTH:
    LOGIN_SUCCESS: 'AUTH:LOGIN_SUCCESS'
    LOGIN_FAILURE: 'AUTH:LOGIN_FAILURE'
    LOGOUT: 'AUTH:LOGOUT'

  ADMIN:
    FORMS:
      LOAD: 'ADMIN:FORMS:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORMS:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORMS:LOAD_FAILURE'
      CREATE: 'ADMIN:FORMS:CREATE'
      CREATE_SUCCESS: 'ADMIN:FORMS:CREATE_SUCCESS'
      CREATE_FAILURE: 'ADMIN:FORMS:CREATE_FAILURE'
    FORM:
      LOAD: 'ADMIN:FORM:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORM:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORM:LOAD_FAILURE'
      UPDATE: 'ADMIN:FORM:UPDATE'
      UPDATE_SUCCESS: 'ADMIN:FORM:UPDATE_SUCCESS'
      UPDATE_FAILURE: 'ADMIN:FORM:UPDATE_FAILURE'
      DESTROY: 'ADMIN:FORM:DESTROY'
      DESTROY_SUCCESS: 'ADMIN:FORM:DESTROY_SUCCESS'
      DESTROY_FAILURE: 'ADMIN:FORM:DESTROY_FAILURE'
    EVENTS:
      LOAD: 'ADMIN:EVENTS:LOAD'
      LOAD_SUCCESS: 'ADMIN:EVENTS:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:EVENTS:LOAD_FAILURE'
      CREATE: 'ADMIN:EVENTS:CREATE'
      CREATE_SUCCESS: 'ADMIN:EVENTS:CREATE_SUCCESS'
      CREATE_FAILURE: 'ADMIN:EVENTS:CREATE_FAILURE'
    EVENT:
      LOAD: 'ADMIN:EVENT:LOAD'
      LOAD_SUCCESS: 'ADMIN:EVENT:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:EVENT:LOAD_FAILURE'
      UPDATE: 'ADMIN:EVENT:UPDATE'
      UPDATE_SUCCESS: 'ADMIN:EVENT:UPDATE_SUCCESS'
      UPDATE_FAILURE: 'ADMIN:EVENT:UPDATE_FAILURE'
      DESTROY: 'ADMIN:EVENT:DESTROY'
      DESTROY_SUCCESS: 'ADMIN:EVENT:DESTROY_SUCCESS'
      DESTROY_FAILURE: 'ADMIN:EVENT:DESTROY_FAILURE'
