module.exports =
  AUTH:
    LOGIN:  'AUTH:LOGIN'
    LOGOUT: 'AUTH:LOGOUT'

  ADMIN:
    FORMS:
      LOAD: 'ADMIN:FORMS:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORMS:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORMS:LOAD_FAILURE'
    FORM:
      LOAD: 'ADMIN:FORM:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORM:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORM:LOAD_FAILURE'
      UPDATE: 'ADMIN:FORM:UPDATE'
      UPDATE_SUCCESS: 'ADMIN:FORM:UPDATE_SUCCESS'
      UPDATE_FAILURE: 'ADMIN:FORM:UPDATE_FAILURE'
