module.exports =
  AUTH:
    LOGIN:  'AUTH:LOGIN'
    LOGOUT: 'AUTH:LOGOUT'

  ADMIN:
    FORMS:
      LOAD: 'ADMIN:FORMS:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORMS:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORMS:LOAD_FAILURE'
      CREATE: 'ADMIN:FORMS:CREATE'
      CREATE_SUCCESS: 'ADMIN:FORMS:CREATE_SUCCESS'
      CREATE_FAILURE: 'ADMIN:FORMS:CREATE_FAILURE'
    FORM:
      LOAD: 'ADMIN:FORM:LOAD'
      LOAD_SUCCESS: 'ADMIN:FORM:LOAD_SUCCESS'
      LOAD_FAILURE: 'ADMIN:FORM:LOAD_FAILURE'
      UPDATE: 'ADMIN:FORM:UPDATE'
      UPDATE_SUCCESS: 'ADMIN:FORM:UPDATE_SUCCESS'
      UPDATE_FAILURE: 'ADMIN:FORM:UPDATE_FAILURE'
      DESTROY: 'ADMIN:FORM:DESTROY'
      DESTROY_SUCCESS: 'ADMIN:FORM:DESTROY_SUCCESS'
      DESTROY_FAILURE: 'ADMIN:FORM:DESTROY_FAILURE'
